version: '3'


services:
        nginx:
                image: od-nginx-image
                ports: 
                   - 80:80
                restart: always
                depends_on:
                   - "onedown"
        onedown: 
                image: od-onedown-image
                restart: always
        cassy:
                image: cassandra:latest
                volumes:
                        - /var/lib/cassy:/var/lib/cassandra
                restart: always


